version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:latest
    steps:
    - checkout
    - run:
        name: Update Conda
        command: |
          conda config --set always_yes True
          conda config --prepend channels conda-forge
          conda update --all
          conda install --quiet --yes --file requirements.txt
  test:
    docker:
      - image: continuumio/miniconda3:latest
    steps:
    - checkout
    - run:
        name: Update Versions
        command: 'python conda_forge_tick/migrate_update_version.py'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
