version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:latest
    steps:
    - checkout
    - run:
        name: Update Conda
        command: |
          conda config --set always_yes True
          sudo conda config --add channels conda-forge
          conda config --set channel_priority strict
          
          conda config --prepend channels conda-forge
          conda install conda 
          conda update conda
          conda info
          conda config --show-sources
          conda list --show-channel-urls
    
    - run: sudo conda install --quiet --yes --file requirements.txt
    - run: sudo conda install --quiet --yes --file requirements/run
    - run: sudo pip install yaml
    - run: sudo conda update conda
               
    - run:
        name: Load Sources
        command: 'python conda_forge_tick/update_sources.py'
        
    - run:
        name: Update Versions
        command: 'python conda_forge_tick/migrate_update_version.py'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
