version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
    - image: continuumio/miniconda3:latest
    steps:
    - checkout
    - python/load-cache
    - run:
        name: Update Conda
        command: |
          conda config --set always_yes True
          conda config --prepend channels conda-forge
          conda update --all
          conda install --quiet --yes --file requirements.txt
    - python/save-cache
    - run:
      command: python conda_forge_tick/migrate_update_version.py  
      name: update_versions

workflows:
  main:
    jobs:
      - build-and-test
